/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package telas;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.RowSorter;
import javax.swing.event.DocumentEvent;
import javax.swing.event.DocumentListener;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableModel;
import javax.swing.table.TableRowSorter;
import model.Pessoa;
import persistencia.Conexao;
import persistencia.PessoaDAO;
import persistencia.PessoaDAOImp;

/**
 *
 * @author aluno
 */
public class ListarPessoas extends javax.swing.JDialog {

    /**
     * Creates new form ListarPessoas
     */
    public ListarPessoas(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        preenchertabela();
        configurarCampoPesquisa();
    }
     private void configurarCampoPesquisa(){
    jTextField1.getDocument().addDocumentListener(new DocumentListener(){
    @Override
    public void insertUpdate(DocumentEvent e){pesquisar();     }
    @Override
    public void removeUpdate(DocumentEvent e){  pesquisar();      }

        @Override
        public void changedUpdate(DocumentEvent e) {pesquisar();}
    }
    );
}
  private void preenchertabela(){
        DefaultTableModel modelo  =  new DefaultTableModel();
        modelo.addColumn("id");
        modelo.addColumn("nome");
        modelo.addColumn("email");
        modelo.addColumn("datanasc");
        try {
            PessoaDAOImp dao= new PessoaDAOImp();
            List<Pessoa> res = dao.Listar();
            for (Pessoa re : res){
                modelo.addRow(
                new Object[]{
                    re.getId(),
                    re.getNome(),
                    re.getEmail(),
                    re.getDatanasc()
                }
                );
            }
           jTable1.setModel(modelo);
      } catch (Exception e) {
      }
            
      /*
        modelo.addRow(new Object[]{"1","jack","18"});
        modelo.addRow(new Object[]{"2","feh","29"});
        modelo.addRow(new Object[]{"3","josé","45"});
        modelo.addRow(new Object[]{"4","fernando","26"});
        jTable1.setModel(modelo);*/
        
       //TableColumnModel modelo2 = jTable1.getColumnModel();
        //modelo2.removeColumn(modelo2.getColumn(0));
        
        RowSorter<TableModel> ordenador = new TableRowSorter<TableModel>(modelo);
        jTable1.setRowSorter(ordenador);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        jButton1.setText("Remover");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Atualizar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(98, 98, 98)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(148, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton1)
                .addGap(18, 18, 18))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 222, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        pesquisar();
    }   
        private void pesquisar(){
        DefaultTableModel modelo= (DefaultTableModel) jTable1.getModel();
       TableRowSorter filtro = new TableRowSorter(modelo);
        jTable1.setRowSorter(filtro);
        String termo =jTextField1.getText();
        if (termo.length()==0){
        filtro.setRowFilter(null);
        }else{
        filtro.setRowFilter(RowFilter.regexFilter(termo));
        }   // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed
        
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    
    int pos = jTable1.convertRowIndexToModel(jTable1.getSelectedRow());// TODO add your handling code here:
        if (pos <= 0){
            JOptionPane.showConfirmDialog(rootPane,"selecione uma linha traste");
        }else{
            DefaultTableModel modelo = (DefaultTableModel)jTable1.getModel();
            modelo.removeRow(pos);
            String msg = jTable1.getModel().getValueAt(pos, 0).toString();
            int id = Interger.parseInt(msg);
            try {
                PessoaDAOImp dao  = new PessoaDAOImp();
                dao.Remover(id);
                preenchertabela();
            } catch (Exception e) {
               // Logger.getLogger(ListarPessoas.class.getName()).log(record);
            }
            
        }
    }//GEN-LAST:event_jButton1ActionPerformed
       

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ListarPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ListarPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ListarPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ListarPessoas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                ListarPessoas dialog = new ListarPessoas(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables

   

    private static class Interger {

        private static int parseInt(String a) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public Interger() {
        }
    }

}
